#!/usr/bin/env node

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');
const { SKILL_SOURCE, CLIENTS, clientDetected, skillTarget, loadTemplates, templateFor } = require('./lib');

// Sibling lenses of the same family: one shared core, one `ai_docs/` tree, a different
// fidelity discipline each. Keyed by the installed skill directory name.
const SIBLING_LENSES = {
  'kb-agentic': 'knowledge',
  'agentic-sdlc': 'code',
};

const cwd = process.cwd();

// 1. Directory layout (canonical mkt_docs structure)
const directories = [
  'mkt_docs',
  'mkt_docs/vision',
  'mkt_docs/research',
  'mkt_docs/strategy',
  'mkt_docs/tactics',
  'mkt_docs/deliverables',
  'mkt_docs/audit',
  'mkt_docs/spikes',
].map((d) => path.join(cwd, d));

// 2. Project protocol (thin pointer — the operating contract is the skill).
// Deliberately short: duplicating the skill's rules here made them drift.
const protocolContent = `# Marketing Agentic SDLC — Project Protocol (pointer)

This project follows the Marketing Agentic SDLC Evidence-First process. The full
operating contract is the \`mkt-agentic-sdlc\` skill (installed in your agent's
skills directory); this file is only the minimal always-on pointer.

## Rule Zero — Triage every request
- E1 Quick: single question or asset feedback (positioning opinion, copy critique). Answer directly; numbers still need a source.
- E2 Campaign: single-campaign or single-channel plan. Light path: mini-brief + targeted research + campaign document.
- E3 Full Plan: complete marketing plan. Full SOSTAC workflow via the skill: Discovery -> Research -> Situation -> Objectives -> Strategy -> Tactics -> Action -> Control -> Packaging.
- Research Spike: time-boxed market question; outcome in \`mkt_docs/spikes/RESEARCH_[topic].md\`.
- When in doubt, pick the higher level. Declare the chosen level when starting.

## The three non-negotiables
1. Evidence ledger: every market number carries an [EV-nn] reference (FACT / BENCHMARK / ASSUMPTION). No invented numbers, ever.
2. Ask only what the user owns: facts come from the user, analysis comes from research. Never ask the user to do the analysis.
3. Internal consistency: budget sums, funnel math and the objective->tactic->KPI chain are validated mechanically before delivery.

## Where things live
- Vision (gate for E3): \`mkt_docs/vision/MKT_VISION.md\` — \`Status: DRAFT\` informs, \`Status: APPROVED\` binds.
- Evidence: \`mkt_docs/research/evidence_ledger.md\` (the single source for every number).
- Strategy artifacts: \`mkt_docs/strategy/\`; tactical artifacts: \`mkt_docs/tactics/\`; final deliverables: \`mkt_docs/deliverables/\`.
- Must-reads: \`mkt_docs/README.md\`; full generated manifest: \`mkt_docs/INDEX.md\`.
- If devPNT is available for this project, its M-VISION / plans / governed artifacts take over (Hybrid mode — see the skill).

## Closure gate
Deliverables ship only after \`python <skill_dir>/scripts/mkt_check.py check\` is
CLEAN (where the validator is adopted) and the CMO review passed.

If the mkt-agentic-sdlc skill is not available in this client, ask the user to install it:
\`npm i -g @antoneeo/mkt-agentic-sdlc-skill\` (the skill installs automatically;
if npm blocks scripts, run \`npx mkt-sdlc-install-skill\`).
`;

console.log('🚀 Initializing Marketing Agentic SDLC workflow...');

// 3. Load templates from the single source (skill's templates.md)
let sections;
try {
  sections = loadTemplates();
} catch (err) {
  console.error(`❌ Cannot load templates: ${err.message}`);
  process.exit(1);
}

let seedFiles;
try {
  seedFiles = [
    ['mkt_docs/README.md', templateFor(sections, 'mkt_docs/README.md')],
    ['mkt_docs/vision/MKT_VISION.md', templateFor(sections, 'MKT_VISION.md')],
    ['mkt_docs/vision/principles.md', templateFor(sections, 'principles.md')],
    ['mkt_docs/research/evidence_ledger.md', templateFor(sections, 'evidence_ledger.md')],
    // NOTE: INDEX.md is NOT seeded — it is generated by `mkt_check.py index`
    // and would immediately fail validate.
  ];
} catch (err) {
  console.error(`❌ ${err.message}`);
  process.exit(1);
}

// 4. Create directories
directories.forEach((dir) => {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
    console.log(`📁 Created directory: ${path.relative(cwd, dir)}`);
  }
});

// 5. Write seed files (never overwrite)
const writeIfNotExists = (relPath, content, description) => {
  const filePath = path.join(cwd, relPath);
  if (!fs.existsSync(filePath)) {
    fs.writeFileSync(filePath, content, 'utf8');
    console.log(`📄 Created file: ${relPath}${description ? ` (${description})` : ''}`);
    return true;
  }
  console.log(`⏭️  Skipped: ${relPath} already exists.`);
  return false;
};

seedFiles.forEach(([relPath, content]) => writeIfNotExists(relPath, content));

// 6. Client discovery and protocol pointers
console.log('\n--- Environment Analysis ---');

const protocolFiles = {
  claude: 'CLAUDE.md',
  gemini: 'GEMINI.md',
  codex: 'AGENTS.md',
  antigravity: 'AGENTS.md', // Antigravity CLI reads AGENTS.md; single protocolContent reused.
};

// A protocol pointer that ALREADY existed was written by someone else — typically a
// sibling lens's init, which seeded the project with its own triage ladder. This init
// must not overwrite it (create-only is the T1 guarantee), so the second ladder is
// written aside and merged by hand.
let protocolPreexisting = false;

for (const client of CLIENTS) {
  if (clientDetected(client)) {
    console.log(`✅ ${client.label} detected.`);
    const created = writeIfNotExists(protocolFiles[client.key], protocolContent, `${client.label} protocol pointer`);
    if (!created) protocolPreexisting = true;
  }
}

// Cursor/Windsurf (always recommended)
writeIfNotExists('.cursorrules', protocolContent, 'Cursor/Windsurf rules');

// 6b. Sibling lenses: additive only. Never edits a user-authored root file.
function installedSiblingLenses() {
  const found = new Map();
  for (const client of CLIENTS) {
    if (!clientDetected(client)) continue;
    const skillsDir = path.dirname(skillTarget(client));
    for (const [dirName, lens] of Object.entries(SIBLING_LENSES)) {
      if (fs.existsSync(path.join(skillsDir, dirName))) found.set(dirName, lens);
    }
  }
  return found;
}

const siblings = installedSiblingLenses();
if (siblings.size > 0) {
  const list = [...siblings].map(([dir, lens]) => `- \`${dir}\` — the **${lens}** lens`).join('\n');
  console.log(`\n🔀 Sibling lens detected: ${[...siblings.keys()].join(', ')}.`);
  const wrote = writeIfNotExists('AGENTIC_MULTI_LENS.md', `# Multi-lens project — routing note (additive)

This project has more than one lens of the Agentic SDLC family installed:

${list}
- \`agentic-sdlc\` — the **code** lens

One \`ai_docs/\` tree, one project default (\`default_domain:\` in \`ai_docs/README.md\`),
one lens per unit of work. Before acting on any L2, L3 or Spike, run the domain router
in the skill's \`routing.md\`: it decides which lens's method and validation rules govern
that unit. L1 never reaches it. Never refer to a document whose meaning differs by lens
("threat model", "vision", \`principles.md\`, \`handoff.md\`) by its bare name.

${protocolPreexisting ? `**Merge step owed.** The always-on protocol pointer of this project (\`CLAUDE.md\` /
\`GEMINI.md\` / \`AGENTS.md\` / \`.cursorrules\`) was written by another lens's init and
carries ITS triage ladder. This init did not overwrite it. Add the marketing lens's ladder
to that file by hand — the pointer below — so both are always loaded.

## Rule Zero — Triage every request (marketing lens)
- E1 Question: one answer from the existing plan, no document written.
- E2 Campaign: a single campaign or channel, on an approved strategy.
- E3 Full engagement: the nine-phase SOSTAC workflow, evidence ledger and all
  three validator gates.
` : `The always-on protocol pointer for the marketing lens was created by this init. When you
install another lens over this project, its init will leave its own ladder here for you
to merge.
`}
This file is NOT auto-loaded by any client: it is a note for you, deliberately additive.
Delete it once the merge is done.
`, 'multi-lens routing note');
  if (wrote && protocolPreexisting) {
    console.log('   ⚠️  A protocol pointer already existed and was NOT overwritten.');
    console.log('       Merge the code-lens ladder from AGENTIC_MULTI_LENS.md into it by hand.');
  }
}

// 7. Generate mkt_docs/INDEX.md so the very first `validate` is already clean.
// The manifest is generated, never seeded: delegate to the validator if Python is available.
const validator = path.join(SKILL_SOURCE, 'scripts', 'mkt_check.py');
let indexed = false;
for (const py of ['python', 'python3', 'py']) {
  try {
    execSync(`${py} "${validator}" index --root "${cwd}"`, { stdio: 'ignore' });
    console.log('📇 Generated mkt_docs/INDEX.md (document manifest).');
    indexed = true;
    break;
  } catch (e) { /* try the next interpreter */ }
}
if (!indexed) {
  console.log('ℹ️  Python not found: generate the manifest later with '
    + '"python <skill_dir>/scripts/mkt_check.py index" (validate reports it until then).');
}

console.log('\n✅ Setup completed successfully!');
console.log('💡 Next steps:');
console.log('   1. Make sure the mkt-agentic-sdlc skill is installed (mkt-sdlc-install-skill).');
console.log('   2. Restart/open the project in your AI client so it reads the protocol pointer.');
console.log('   3. Start an E3 engagement: the skill runs Discovery (its questions) before anything else.');
