"""Historical pre-F-058 design probe, not a post-fix regression test.

Its expected marketing/core index mismatch is intentionally obsolete after F-058.
All project writes are confined to temporary directories.
"""
from pathlib import Path
import json
import shutil
import subprocess
import sys
import tempfile

REPO = Path(__file__).resolve().parents[3]
CODE = REPO / "skills/agentic-sdlc-skill/scripts/sdlc_check.py"
MKT = REPO / "distributions/mkt-agentic-sdlc/skills/mkt-agentic-sdlc/scripts/mkt_check.py"
KB = REPO / "distributions/kb-agentic-skill/skills/kb-agentic-skill/scripts/sdlc_check.py"


def run(entry, root, command):
    p = subprocess.run([sys.executable, str(entry), command, "--root", str(root),
                        "--docs-dir", "ai_docs"], capture_output=True, text=True)
    return {"returncode": p.returncode, "stdout": p.stdout.strip()[-600:]}


def main():
    with tempfile.TemporaryDirectory() as temp:
        root = Path(temp)
        docs = root / "ai_docs"
        docs.mkdir()
        (docs / "README.md").write_text("---\ndefault_domain: marketing\n---\n# Docs\n", encoding="utf-8")
        (docs / "vision").mkdir()
        (docs / "vision" / "VISION_probe.md").write_text(
            "---\ndescription: Probe\nstatus: APPROVED\n---\n# Probe\n", encoding="utf-8")
        marketing_index = run(MKT, root, "index")
        legacy = (docs / "INDEX.md").read_bytes()
        core_validation = run(CODE, root, "validate")
        code_index = run(CODE, root, "index")
        core = (docs / "INDEX.md").read_bytes()
        kb_index = run(KB, root, "index")
        kb = (docs / "INDEX.md").read_bytes()
        (docs / "topics").mkdir()
        (docs / "topics" / "loop.md").write_text(
            "---\ndescription: Loop\nparents: [loop]\n---\n# Loop\n", encoding="utf-8")
        graph = run(KB, root, "graph")
        package = root / "package"
        (package / "scripts").mkdir(parents=True)
        shutil.copyfile(REPO / "distributions/mkt-agentic-sdlc/scripts/lib.js", package / "scripts/lib.js")
        skill = package / "skills" / "mkt-agentic-sdlc"
        skill.mkdir(parents=True)
        (skill / "SKILL.md").write_text("---\nname: mkt-agentic-sdlc\n---\n", encoding="utf-8")
        routing = "| Lens | Skill |\n|---|---|\n| marketing | `mkt-agentic-sdlc` |\n| course | `course-creator` |\n"
        (skill / "routing.md").write_text(routing, encoding="utf-8")
        lib = subprocess.run(["node", "-e", "const x=require(process.argv[1]);console.log(JSON.stringify(x.SIBLING_LENSES))",
                              str(package / "scripts/lib.js")], capture_output=True, text=True)
        observed = {
            "marketing_index": marketing_index,
            "core_after_legacy": core_validation,
            "code_index": code_index,
            "kb_index": kb_index,
            "legacy_differs_from_core": legacy != core,
            "code_kb_index_identical": core == kb,
            "kb_graph_self_cycle": graph,
            "course_route_in_node": {"rc": lib.returncode, "stdout": lib.stdout.strip(), "stderr": lib.stderr.strip()[-300:]},
        }
        print(json.dumps(observed, ensure_ascii=False, indent=2))
        # The claims the F-058 Impact rests on. --negate inverts every expectation:
        # the harness must go red under it, or it proves nothing.
        claims = {
            "legacy marketing index starts with the marketing header":
                legacy.startswith(b"# mkt_docs INDEX (generated by mkt_check.py index"),
            "core validate fails on the legacy marketing index":
                core_validation["returncode"] == 1
                and "INDEX.md not aligned" in core_validation["stdout"],
            "legacy index differs from the core index": legacy != core,
            "code and KB write a byte-identical index": core == kb,
            "KB graph reports a topic cycle":
                graph["returncode"] == 1 and "cycle" in graph["stdout"],
            "lib.js accepts the course-creator row":
                lib.returncode == 0
                and json.loads(lib.stdout or "{}") == {"course-creator": "course"},
        }
        return claims


if __name__ == "__main__":
    negate = "--negate" in sys.argv[1:]
    failed = [name for name, ok in main().items() if ok == negate]
    for name in failed:
        print(f"[FAIL] {'(negated) ' if negate else ''}{name}")
    print(f"{len(failed)} claim(s) failed{' under --negate' if negate else ''}")
    sys.exit(1 if failed else 0)
