#!/usr/bin/env node

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');
const { SKILL_SOURCE, CLIENTS, clientDetected, loadTemplates, templateFor } = require('./lib');

const cwd = process.cwd();

// 1. Directory layout (canonical mkt_docs structure)
const directories = [
  'mkt_docs',
  'mkt_docs/vision',
  'mkt_docs/research',
  'mkt_docs/strategy',
  'mkt_docs/tactics',
  'mkt_docs/deliverables',
  'mkt_docs/audit',
  'mkt_docs/spikes',
].map((d) => path.join(cwd, d));

// 2. Project protocol (thin pointer — the operating contract is the skill).
// Deliberately short: duplicating the skill's rules here made them drift.
const protocolContent = `# Marketing Agentic SDLC — Project Protocol (pointer)

This project follows the Marketing Agentic SDLC Evidence-First process. The full
operating contract is the \`mkt-agentic-sdlc\` skill (installed in your agent's
skills directory); this file is only the minimal always-on pointer.

## Rule Zero — Triage every request
- E1 Quick: single question or asset feedback (positioning opinion, copy critique). Answer directly; numbers still need a source.
- E2 Campaign: single-campaign or single-channel plan. Light path: mini-brief + targeted research + campaign document.
- E3 Full Plan: complete marketing plan. Full SOSTAC workflow via the skill: Discovery -> Research -> Situation -> Objectives -> Strategy -> Tactics -> Action -> Control -> Packaging.
- Research Spike: time-boxed market question; outcome in \`mkt_docs/spikes/RESEARCH_[topic].md\`.
- When in doubt, pick the higher level. Declare the chosen level when starting.

## The three non-negotiables
1. Evidence ledger: every market number carries an [EV-nn] reference (FACT / BENCHMARK / ASSUMPTION). No invented numbers, ever.
2. Ask only what the user owns: facts come from the user, analysis comes from research. Never ask the user to do the analysis.
3. Internal consistency: budget sums, funnel math and the objective->tactic->KPI chain are validated mechanically before delivery.

## Where things live
- Vision (gate for E3): \`mkt_docs/vision/MKT_VISION.md\` — \`Status: DRAFT\` informs, \`Status: APPROVED\` binds.
- Evidence: \`mkt_docs/research/evidence_ledger.md\` (the single source for every number).
- Strategy artifacts: \`mkt_docs/strategy/\`; tactical artifacts: \`mkt_docs/tactics/\`; final deliverables: \`mkt_docs/deliverables/\`.
- Must-reads: \`mkt_docs/README.md\`; full generated manifest: \`mkt_docs/INDEX.md\`.
- If devPNT is available for this project, its M-VISION / plans / governed artifacts take over (Hybrid mode — see the skill).

## Closure gate
Deliverables ship only after \`python <skill_dir>/scripts/mkt_check.py check\` is
CLEAN (where the validator is adopted) and the CMO review passed.

If the mkt-agentic-sdlc skill is not available in this client, ask the user to install it:
\`npm i -g @antoneeo/mkt-agentic-sdlc-skill && mkt-sdlc-install-skill\`
`;

console.log('🚀 Initializing Marketing Agentic SDLC workflow...');

// 3. Load templates from the single source (skill's templates.md)
let sections;
try {
  sections = loadTemplates();
} catch (err) {
  console.error(`❌ Cannot load templates: ${err.message}`);
  process.exit(1);
}

let seedFiles;
try {
  seedFiles = [
    ['mkt_docs/README.md', templateFor(sections, 'mkt_docs/README.md')],
    ['mkt_docs/vision/MKT_VISION.md', templateFor(sections, 'MKT_VISION.md')],
    ['mkt_docs/vision/principles.md', templateFor(sections, 'principles.md')],
    ['mkt_docs/research/evidence_ledger.md', templateFor(sections, 'evidence_ledger.md')],
    // NOTE: INDEX.md is NOT seeded — it is generated by `mkt_check.py index`
    // and would immediately fail validate.
  ];
} catch (err) {
  console.error(`❌ ${err.message}`);
  process.exit(1);
}

// 4. Create directories
directories.forEach((dir) => {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
    console.log(`📁 Created directory: ${path.relative(cwd, dir)}`);
  }
});

// 5. Write seed files (never overwrite)
const writeIfNotExists = (relPath, content, description) => {
  const filePath = path.join(cwd, relPath);
  if (!fs.existsSync(filePath)) {
    fs.writeFileSync(filePath, content, 'utf8');
    console.log(`📄 Created file: ${relPath}${description ? ` (${description})` : ''}`);
    return true;
  }
  console.log(`⏭️  Skipped: ${relPath} already exists.`);
  return false;
};

seedFiles.forEach(([relPath, content]) => writeIfNotExists(relPath, content));

// 6. Client discovery and protocol pointers
console.log('\n--- Environment Analysis ---');

const protocolFiles = {
  claude: 'CLAUDE.md',
  gemini: 'GEMINI.md',
  codex: 'AGENTS.md',
  antigravity: 'AGENTS.md', // Antigravity CLI reads AGENTS.md; single protocolContent reused.
};

for (const client of CLIENTS) {
  if (clientDetected(client)) {
    console.log(`✅ ${client.label} detected.`);
    writeIfNotExists(protocolFiles[client.key], protocolContent, `${client.label} protocol pointer`);
  }
}

// Cursor/Windsurf (always recommended)
writeIfNotExists('.cursorrules', protocolContent, 'Cursor/Windsurf rules');

// 7. Generate mkt_docs/INDEX.md so the very first `validate` is already clean.
// The manifest is generated, never seeded: delegate to the validator if Python is available.
const validator = path.join(SKILL_SOURCE, 'scripts', 'mkt_check.py');
let indexed = false;
for (const py of ['python', 'python3', 'py']) {
  try {
    execSync(`${py} "${validator}" index --root "${cwd}"`, { stdio: 'ignore' });
    console.log('📇 Generated mkt_docs/INDEX.md (document manifest).');
    indexed = true;
    break;
  } catch (e) { /* try the next interpreter */ }
}
if (!indexed) {
  console.log('ℹ️  Python not found: generate the manifest later with '
    + '"python <skill_dir>/scripts/mkt_check.py index" (validate reports it until then).');
}

console.log('\n✅ Setup completed successfully!');
console.log('💡 Next steps:');
console.log('   1. Make sure the mkt-agentic-sdlc skill is installed (mkt-sdlc-install-skill).');
console.log('   2. Restart/open the project in your AI client so it reads the protocol pointer.');
console.log('   3. Start an E3 engagement: the skill runs Discovery (its questions) before anything else.');
