#!/usr/bin/env node

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');
const { SKILL_SOURCE, CLIENTS, clientDetected, loadTemplates, templateFor } = require('./lib');

const cwd = process.cwd();

// 1. Directory layout (canonical ai_docs structure, including reference/)
const directories = [
  'ai_docs',
  'ai_docs/vision',
  'ai_docs/vision/features',
  'ai_docs/reference',
  'ai_docs/strategic',
  'ai_docs/audit',
  'ai_docs/solutions',
].map((d) => path.join(cwd, d));

// 2. Project protocol (thin pointer — the operating contract is the skill).
// Deliberately short: duplicating the skill's rules here made them drift.
const protocolContent = `# Agentic SDLC — Project Protocol (pointer)

This project follows the Agentic SDLC Documentation-First process. The full
operating contract is the \`agentic-sdlc\` skill (installed in your agent's
skills directory); this file is only the minimal always-on pointer.

## Rule Zero — Triage every request
- L1 Trivial: ~10 lines, 1-2 files, no API/dependency/behavior change. Implement + run existing tests; no docs.
- L2 Small: clear root cause, at most 3 files, low risk. Mini-analysis in the reply; tests mandatory.
- L3 Significant: >3 files, APIs/contracts, new dependency, user-visible behavior, security-sensitive area, or architectural change. Full workflow via the skill: Vision Gate -> ANALYSIS -> plan -> implement -> test -> closure.
- Spike: time-boxed exploration; outcome in \`ai_docs/solutions/SPIKE_[topic].md\`; reclassify for production.
- Security-sensitive areas (external input parsing, authN/authZ, crypto, network, personal data, filesystem) are never L1.
- When in doubt, pick the higher level. Declare the chosen level when starting.

## Where things live
- Vision (gate for L3): \`ai_docs/vision/\` — \`Status: DRAFT\` informs, \`Status: APPROVED\` binds.
- Feature analyses: \`ai_docs/solutions/ANALYSIS_[feature].md\` (frontmatter = feature state).
- Must-reads: \`ai_docs/README.md\`; full generated manifest: \`ai_docs/INDEX.md\`.
- If devPNT is available for this project, its M-VISION / plans / governed artifacts take over (Hybrid mode — see the skill).

## Closure gate
Docs travel in the same commit/PR as the code they describe. If the project
adopts the validator, \`python <skill_dir>/scripts/sdlc_check.py check\` must be
CLEAN before declaring work done.

If the agentic-sdlc skill is not available in this client, ask the user to install it:
\`npm i -g @antoneeo/agentic-sdlc-skill && agentic-sdlc-install-skill\`
`;

console.log('🚀 Initializing Agentic SDLC workflow...');

// 3. Load templates from the single source (skill's templates.md)
let sections;
try {
  sections = loadTemplates();
} catch (err) {
  console.error(`❌ Cannot load templates: ${err.message}`);
  process.exit(1);
}

// audit_plan: the template block carries illustrative rows; a fresh project
// starts from a single root PENDING row instead.
function initialAuditPlan() {
  const tpl = templateFor(sections, 'audit_plan.md');
  const lines = tpl.split('\n');
  const sepIdx = lines.findIndex((l) => /^\|[-\s|:]+\|$/.test(l.trim()));
  if (sepIdx === -1) return tpl; // unexpected shape: keep the template as-is
  return lines.slice(0, sepIdx + 1).join('\n') + '\n| / | PENDING | - | Initial analysis |\n';
}

let seedFiles;
try {
  seedFiles = [
    ['ai_docs/README.md', templateFor(sections, 'ai_docs/README.md')],
    ['ai_docs/vision/project_vision.md', templateFor(sections, 'project_vision.md')],
    ['ai_docs/vision/roadmap.md', templateFor(sections, 'vision/roadmap.md')],
    ['ai_docs/vision/principles.md', templateFor(sections, 'principles.md')],
    ['ai_docs/strategic/architecture.md', templateFor(sections, 'architecture.md and existing_features.md', 0)],
    ['ai_docs/strategic/existing_features.md', templateFor(sections, 'architecture.md and existing_features.md', 1)],
    ['ai_docs/audit/audit_plan.md', initialAuditPlan()],
    // NOTE: features_history.md and INDEX.md are NOT seeded — they are
    // generated by `sdlc_check.py index` and would immediately fail validate.
  ];
} catch (err) {
  console.error(`❌ ${err.message}`);
  process.exit(1);
}

// 4. Create directories
directories.forEach((dir) => {
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
    console.log(`📁 Created directory: ${path.relative(cwd, dir)}`);
  }
});

// 5. Write seed files (never overwrite)
const writeIfNotExists = (relPath, content, description) => {
  const filePath = path.join(cwd, relPath);
  if (!fs.existsSync(filePath)) {
    fs.writeFileSync(filePath, content, 'utf8');
    console.log(`📄 Created file: ${relPath}${description ? ` (${description})` : ''}`);
    return true;
  }
  console.log(`⏭️  Skipped: ${relPath} already exists.`);
  return false;
};

seedFiles.forEach(([relPath, content]) => writeIfNotExists(relPath, content));

// 6. Client discovery and protocol pointers
console.log('\n--- Environment Analysis ---');

const protocolFiles = {
  claude: 'CLAUDE.md',
  gemini: 'GEMINI.md',
  codex: 'AGENTS.md',
};

for (const client of CLIENTS) {
  if (clientDetected(client)) {
    console.log(`✅ ${client.label} detected.`);
    writeIfNotExists(protocolFiles[client.key], protocolContent, `${client.label} protocol pointer`);
  }
}

// Cursor/Windsurf (always recommended)
writeIfNotExists('.cursorrules', protocolContent, 'Cursor/Windsurf rules');

// 7. Generate ai_docs/INDEX.md so the very first `validate` is already clean.
// The manifest is generated, never seeded: delegate to the validator if Python is available.
const validator = path.join(SKILL_SOURCE, 'scripts', 'sdlc_check.py');
let indexed = false;
for (const py of ['python', 'python3', 'py']) {
  try {
    execSync(`${py} "${validator}" index --root "${cwd}"`, { stdio: 'ignore' });
    console.log('📇 Generated ai_docs/INDEX.md (document manifest).');
    indexed = true;
    break;
  } catch (e) { /* try the next interpreter */ }
}
if (!indexed) {
  console.log('ℹ️  Python not found: generate the manifest later with '
    + '"python <skill_dir>/scripts/sdlc_check.py index" (validate reports it until then).');
}

console.log('\n✅ Setup completed successfully!');
console.log('💡 Next steps:');
console.log('   1. Make sure the agentic-sdlc skill is installed (agentic-sdlc-install-skill).');
console.log('   2. Restart/open the project in your AI client so it reads the protocol pointer.');
console.log('   3. Start with an audit following ai_docs/audit/audit_plan.md.');
