#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""The drift guard — the family's spine is authored once and copied verbatim.

Three distributions ship the same spine. Nothing but this guard stops the fourth
divergence: the first three happened silently, and were found by a user.

How it works, and why this shape:
  * SHARED_FILES is an explicit per-file MANIFEST, never "everything" and never a
    directory glob. A file leaving the shared set is then a reviewable change to
    this list, not an absence nobody notices.
  * `python shared_files.py --update` records each shared file's SHA-256 into
    `shared_manifest.json`. The recorded content is IDENTICAL in every
    distribution — that is the whole trick: edit a shared file in one repo and its
    manifest changes, so the three manifests no longer match and the divergence is
    visible as a diff instead of as a bug report.
  * `test_drift.py` fails when a shared file's hash does not match the manifest.
    So a local edit is caught immediately, in the repo where it happened, and the
    only way to make it green is to regenerate — which is exactly the moment to
    copy the file to its siblings.

Hashing is LF-normalized: the corpus is checked out on Windows and POSIX, and a
line-ending difference is not divergence.
"""

import hashlib
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
SKILL_DIR = HERE.parent
MANIFEST = HERE / "shared_manifest.json"

# Paths are relative to the SKILL directory. Every entry is a file that MUST be
# byte-identical (modulo line endings) in every distribution of the family.
SHARED_FILES = (
    # the spine itself
    "scripts/sdlc_core.py",
    "scripts/entry_point.py",
    "scripts/shared_files.py",
    # the shared batteries: a test that differs between distributions is a test
    # that stopped being shared
    "scripts/test_skill_invariants.py",
    "scripts/test_domain_rules.py",
    "scripts/test_docs_root.py",
    "scripts/test_session_start.py",
    "scripts/test_plan.py",
    "scripts/test_drift.py",
    # domain-neutral doctrine
    "review.md",
    "routing.md",
    "vision.md",
    "guides.md",
    "dispatch.md",
)

# Deliberately NOT shared, and named here so the absence reads as a decision:
#   SKILL.md, templates.md, ENFORCEMENT.md  -- each domain's own wording
#   the entry point (sdlc_check.py / mkt_check.py) -- that IS the domain
#   the overlay files (architect/tdd/debugging | taxonomy/distillation |
#     frameworks/research) -- the overlays are supposed to differ
#   the golden corpus, its baseline AND its harness -- the harness is bound to the
#     corpus and to the subcommands THIS distribution ships (marketing has ledger,
#     budget, funnel, trace and no orient), and its whole job is to freeze what this
#     distribution does. Uniformity there would defeat the purpose
NOT_SHARED_ON_PURPOSE = (
    "SKILL.md", "templates.md", "ENFORCEMENT.md",
    "scripts/sdlc_check.py", "scripts/mkt_check.py",
    "scripts/test_golden_regression.py",
)


def digest(path):
    """SHA-256 of the LF-normalized bytes: a CRLF checkout is not divergence."""
    data = path.read_bytes().replace(b"\r\n", b"\n")
    return hashlib.sha256(data).hexdigest()


def current():
    out = {}
    for rel in SHARED_FILES:
        p = SKILL_DIR / rel
        out[rel] = digest(p) if p.is_file() else None
    return out


def recorded():
    if not MANIFEST.is_file():
        return None
    return json.loads(MANIFEST.read_text(encoding="utf-8"))["files"]


def update():
    MANIFEST.write_text(
        json.dumps({
            "_comment": "Generated by shared_files.py --update. IDENTICAL in every "
                        "distribution of the family: if two copies of this file differ, "
                        "the spine has diverged. Never edit by hand.",
            "files": current(),
        }, indent=2, sort_keys=True) + "\n",
        encoding="utf-8", newline="\n")
    return MANIFEST


def report():
    """(missing, changed) against the recorded manifest."""
    rec = recorded()
    if rec is None:
        return SHARED_FILES, ()
    cur = current()
    missing = tuple(rel for rel, h in cur.items() if h is None)
    changed = tuple(rel for rel, h in cur.items()
                    if h is not None and rec.get(rel) != h)
    return missing, changed


if __name__ == "__main__":
    if "--update" in sys.argv:
        print(f"[ok] shared manifest written: {update()}")
        print("     Now copy every changed shared file to the sibling distributions "
              "and regenerate there too, or their guard will fail.")
        sys.exit(0)
    miss, chg = report()
    for rel in miss:
        print(f"[ERROR] shared file missing: {rel}")
    for rel in chg:
        print(f"[ERROR] shared file diverged from the manifest: {rel}")
    if miss or chg:
        print("\nThe spine is authored once and copied verbatim. Either restore the file,\n"
              "or -- if the change is intended -- apply it to EVERY distribution and run\n"
              "`python shared_files.py --update` in each.")
        sys.exit(1)
    print(f"[ok] {len(SHARED_FILES)} shared files match the manifest")
